import importlib.machinery
import importlib.util
import io
import os
import shutil
import struct
import subprocess
import tempfile
import unittest
from pathlib import Path

PYTHON_CRATE_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = PYTHON_CRATE_ROOT.parent
TESTDATA_DIR = PYTHON_CRATE_ROOT / "testdata"
TEST_M4A = TESTDATA_DIR / "test.m4a"
# Rich-metadata fixture generated by testdata/regenerate.sh via ffmpeg.
# Contains: ©nam, ©ART, ©alb, ©day, ©too, ©cmt, ©gen, trkn iTunes tags.
TAGGED_M4A = TESTDATA_DIR / "tagged_tone.m4a"


class WriteOnlyBytes:
    def __init__(self):
        self.chunks = []
        self.flushed = False

    def write(self, data):
        self.chunks.append(bytes(data))
        return len(data)

    def flush(self):
        self.flushed = True

    def getvalue(self):
        return b"".join(self.chunks)


# ---------------------------------------------------------------------------
# Minimal MP4 parser used by the "metadata preservation" tests.
# Locates the AAC sample byte ranges (from stbl) so we can prove every byte
# outside those ranges — i.e. all container metadata: ftyp, moov, udta, meta,
# ilst, stsd, chapter atoms, etc. — is byte-identical after gain adjustment.
# ---------------------------------------------------------------------------


def _find_box(buf, typ, start=0, end=None):
    if end is None:
        end = len(buf)
    off = start
    while off + 8 <= end:
        size = struct.unpack(">I", buf[off : off + 4])[0]
        t = buf[off + 4 : off + 8]
        header = 8
        if size == 1:
            size = struct.unpack(">Q", buf[off + 8 : off + 16])[0]
            header = 16
        elif size == 0:
            size = end - off
        if t == typ:
            return off, size, header
        off += size
    return None


def _parse_gain_metadata(buf):
    try:
        payload = _parse_itunes_tags(buf).get(b"M4AG")
    except TypeError:
        return None

    if not payload:
        return None

    fields = payload.decode("utf-8").split()
    if not fields or fields[0] != "m4againrs":
        return None

    metadata = {}
    for field in fields[1:]:
        if "=" in field:
            key, value = field.split("=", 1)
            metadata[key] = value
    return metadata


def _sample_byte_ranges(buf):
    """Return [(file_offset, size)] for every AAC sample in buf."""
    moov = _find_box(buf, b"moov")
    trak = _find_box(buf, b"trak", moov[0] + moov[2], moov[0] + moov[1])
    mdia = _find_box(buf, b"mdia", trak[0] + trak[2], trak[0] + trak[1])
    minf = _find_box(buf, b"minf", mdia[0] + mdia[2], mdia[0] + mdia[1])
    stbl = _find_box(buf, b"stbl", minf[0] + minf[2], minf[0] + minf[1])
    stbl_s, stbl_end = stbl[0] + stbl[2], stbl[0] + stbl[1]

    stsz = _find_box(buf, b"stsz", stbl_s, stbl_end)
    stsc = _find_box(buf, b"stsc", stbl_s, stbl_end)
    stco = _find_box(buf, b"stco", stbl_s, stbl_end)
    co64 = _find_box(buf, b"co64", stbl_s, stbl_end) if stco is None else None

    stsz_content = stsz[0] + stsz[2]
    default_size = struct.unpack(">I", buf[stsz_content + 4 : stsz_content + 8])[0]
    sample_count = struct.unpack(">I", buf[stsz_content + 8 : stsz_content + 12])[0]
    if default_size != 0:
        sizes = [default_size] * sample_count
    else:
        sizes_start = stsz_content + 12
        sizes = [
            struct.unpack(">I", buf[sizes_start + i * 4 : sizes_start + (i + 1) * 4])[0]
            for i in range(sample_count)
        ]

    stsc_content = stsc[0] + stsc[2]
    stsc_count = struct.unpack(">I", buf[stsc_content + 4 : stsc_content + 8])[0]
    stsc_entries = []
    for i in range(stsc_count):
        off = stsc_content + 8 + i * 12
        stsc_entries.append(
            (
                struct.unpack(">I", buf[off : off + 4])[0],
                struct.unpack(">I", buf[off + 4 : off + 8])[0],
            )
        )

    if stco is not None:
        chunk_content = stco[0] + stco[2]
        chunk_count = struct.unpack(">I", buf[chunk_content + 4 : chunk_content + 8])[0]
        chunk_offsets = [
            struct.unpack(">I", buf[chunk_content + 8 + i * 4 : chunk_content + 12 + i * 4])[0]
            for i in range(chunk_count)
        ]
    else:
        chunk_content = co64[0] + co64[2]
        chunk_count = struct.unpack(">I", buf[chunk_content + 4 : chunk_content + 8])[0]
        chunk_offsets = [
            struct.unpack(">Q", buf[chunk_content + 8 + i * 8 : chunk_content + 16 + i * 8])[0]
            for i in range(chunk_count)
        ]

    ranges = []
    sample_idx = 0
    for chunk_idx, chunk_off in enumerate(chunk_offsets):
        chunk_num = chunk_idx + 1
        spc = stsc_entries[0][1]
        for fc, s in stsc_entries:
            if fc <= chunk_num:
                spc = s
            else:
                break
        off_in_chunk = 0
        for _ in range(spc):
            if sample_idx >= sample_count:
                break
            size = sizes[sample_idx]
            ranges.append((chunk_off + off_in_chunk, size))
            off_in_chunk += size
            sample_idx += 1
    return ranges


def _parse_itunes_tags(buf):
    """Walk moov/udta/meta/ilst/<name>/data and return {name: payload_bytes}."""
    moov = _find_box(buf, b"moov")
    if moov is None:
        return {}
    udta = _find_box(buf, b"udta", moov[0] + moov[2], moov[0] + moov[1])
    if udta is None:
        return {}
    meta = _find_box(buf, b"meta", udta[0] + udta[2], udta[0] + udta[1])
    if meta is None:
        return {}
    ilst = _find_box(buf, b"ilst", meta[0] + meta[2] + 4, meta[0] + meta[1])
    if ilst is None:
        return {}
    ilst_start = ilst[0] + ilst[2]
    ilst_end = ilst[0] + ilst[1]

    tags = {}
    off = ilst_start
    while off + 8 <= ilst_end:
        size = struct.unpack(">I", buf[off : off + 4])[0]
        name = bytes(buf[off + 4 : off + 8])
        data_box = _find_box(buf, b"data", off + 8, off + size)
        if data_box is not None:
            # data box header(8) + type(4) + locale(4) = 16 bytes before payload
            data_start = data_box[0] + 16
            data_end = data_box[0] + data_box[1]
            tags[name] = bytes(buf[data_start:data_end])
        off += size
    return tags


def _find_module():
    env = os.environ.get("M4AGAINRS_PYTHON_MODULE")
    if env:
        path = Path(env)
        if path.exists():
            return path
        raise FileNotFoundError(f"M4AGAINRS_PYTHON_MODULE points to a missing file: {path}")

    suffixes = list(importlib.machinery.EXTENSION_SUFFIXES)
    for fallback_suffix in (".so", ".dylib", ".pyd", ".dll"):
        if fallback_suffix not in suffixes:
            suffixes.append(fallback_suffix)

    candidates = []
    for target_dir in ("debug", "release"):
        for stem in ("libm4againrs", "m4againrs"):
            for suffix in suffixes:
                candidates.append(WORKSPACE_ROOT / "target" / target_dir / f"{stem}{suffix}")

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError(
        "Could not find the built m4againrs extension. "
        "Build it first with `cargo build -p m4againrs-py` "
        "or `cd python && maturin develop`."
    )


def _load_module():
    path = _find_module()
    spec = importlib.util.spec_from_file_location("m4againrs", str(path))
    if spec is None or spec.loader is None:
        if path.suffix in {".dylib", ".dll"}:
            spec = importlib.util.spec_from_file_location(
                "m4againrs",
                str(path),
                loader=importlib.machinery.ExtensionFileLoader("m4againrs", str(path)),
            )

    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load m4againrs module from {path}")

    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


m4againrs = _load_module()


class M4aGainRsTest(unittest.TestCase):
    def test_gain_step_db_constant(self):
        self.assertEqual(m4againrs.GAIN_STEP_DB, 1.5)
        self.assertIn("aac_apply_gain_to_writer", m4againrs.__all__)

    # -- file API --

    def test_file_zero_raises_and_does_not_create_dst(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            before = src.read_bytes()
            with self.assertRaises(RuntimeError):
                m4againrs.aac_apply_gain_file(str(src), str(dst), 0)
            self.assertFalse(dst.exists())
            self.assertEqual(src.read_bytes(), before)

    def test_file_rejects_same_src_dst_and_preserves_file(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            shutil.copy2(TEST_M4A, src)
            before = src.read_bytes()

            with self.assertRaises(RuntimeError):
                m4againrs.aac_apply_gain_file(str(src), str(src), 2)

            self.assertEqual(src.read_bytes(), before)

    def test_file_positive_writes_dst_and_preserves_src(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            original = src.read_bytes()

            modified = m4againrs.aac_apply_gain_file(str(src), str(dst), 2)
            self.assertGreater(modified, 0)

            self.assertTrue(dst.exists())
            dst_bytes = dst.read_bytes()
            self.assertGreater(len(dst_bytes), len(original))
            self.assertTrue(
                any(
                    dst_bytes[off : off + size] != original[off : off + size]
                    for off, size in _sample_byte_ranges(original)
                )
            )
            self.assertEqual(_parse_gain_metadata(dst_bytes)["gain_steps"], "2")
            # src must be untouched
            self.assertEqual(src.read_bytes(), original)

    def test_file_writes_gain_metadata_to_dst_only(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)

            m4againrs.aac_apply_gain_file(str(src), str(dst), -3)

            self.assertIsNone(_parse_gain_metadata(src.read_bytes()))
            metadata = _parse_gain_metadata(dst.read_bytes())
            self.assertEqual(metadata["version"], "1")
            self.assertEqual(metadata["gain_steps"], "-3")
            self.assertEqual(metadata["gain_step_db"], "1.5")

            probe = subprocess.run(
                [
                    "ffprobe",
                    "-hide_banner",
                    "-v",
                    "error",
                    "-show_entries",
                    "format_tags=M4AG",
                    "-of",
                    "default=nw=1",
                    "-export_all",
                    "1",
                    str(dst),
                ],
                check=True,
                stdout=subprocess.PIPE,
                text=True,
            )
            self.assertIn(
                "TAG:M4AG=m4againrs version=1 gain_steps=-3 gain_step_db=1.5",
                probe.stdout,
            )

    def test_file_src_preserved_on_negative_steps(self):
        """Second explicit check: negative gain also leaves src untouched."""
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            original = src.read_bytes()

            m4againrs.aac_apply_gain_file(str(src), str(dst), -3)
            self.assertEqual(src.read_bytes(), original)

    def test_file_nonexistent_raises(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            dst = Path(tmpdir) / "out.m4a"
            with self.assertRaises(RuntimeError):
                m4againrs.aac_apply_gain_file(
                    "/nonexistent/path/file.m4a", str(dst), 2
                )
            self.assertFalse(dst.exists())

    def test_file_non_m4a_raises(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            dst = Path(tmpdir) / "out.m4a"
            with self.assertRaises(RuntimeError):
                m4againrs.aac_apply_gain_file(
                    str(WORKSPACE_ROOT / ".gitignore"), str(dst), 2
                )
            self.assertFalse(dst.exists())

    def test_writer_api_writes_to_binary_stream(self):
        original = TEST_M4A.read_bytes()
        output = WriteOnlyBytes()

        modified = m4againrs.aac_apply_gain_to_writer(str(TEST_M4A), output, 2)

        self.assertGreater(modified, 0)
        self.assertTrue(output.flushed)
        out = output.getvalue()
        self.assertGreater(len(out), len(original))
        self.assertEqual(_parse_gain_metadata(out)["gain_steps"], "2")
        self.assertTrue(
            any(
                out[off : off + size] != original[off : off + size]
                for off, size in _sample_byte_ranges(original)
            )
        )

    def test_writer_api_accepts_bytes_io(self):
        output = io.BytesIO()

        modified = m4againrs.aac_apply_gain_to_writer(str(TEST_M4A), output, -2)

        self.assertGreater(modified, 0)
        out = output.getvalue()
        self.assertEqual(_parse_gain_metadata(out)["gain_steps"], "-2")

    def test_writer_api_output_file_decodes_with_ffmpeg(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            dst = Path(tmpdir) / "streamed_out.m4a"

            with dst.open("wb") as output:
                modified = m4againrs.aac_apply_gain_to_writer(
                    str(TEST_M4A), output, 2
                )

            self.assertGreater(modified, 0)
            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-i",
                    str(dst),
                    "-f",
                    "null",
                    "-",
                ],
                check=True,
            )


class MetadataPreservationTest(unittest.TestCase):
    """Prove that file-backed gain adjustment preserves existing container
    metadata while adding only the custom gain tag."""

    def test_file_api_adds_only_gain_metadata_to_itunes_tags(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            src_bytes = src.read_bytes()
            before_tags = _parse_itunes_tags(src_bytes)

            m4againrs.aac_apply_gain_file(str(src), str(dst), 3)

            # src untouched
            self.assertEqual(src.read_bytes(), src_bytes)

            after_tags = _parse_itunes_tags(dst.read_bytes())
            expected_tags = dict(before_tags)
            expected_tags[b"M4AG"] = b"m4againrs version=1 gain_steps=3 gain_step_db=1.5"
            self.assertEqual(after_tags, expected_tags)

    def test_file_api_preserves_existing_description_tag(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "described.m4a"
            dst = Path(tmpdir) / "described_out.m4a"
            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-i",
                    str(TEST_M4A),
                    "-c",
                    "copy",
                    "-metadata",
                    "description=Existing description",
                    str(src),
                ],
                check=True,
            )
            before_tags = _parse_itunes_tags(src.read_bytes())
            self.assertEqual(before_tags.get(b"desc"), b"Existing description")

            m4againrs.aac_apply_gain_file(str(src), str(dst), 2)

            after_tags = _parse_itunes_tags(dst.read_bytes())
            self.assertEqual(after_tags.get(b"desc"), b"Existing description")
            self.assertEqual(
                after_tags.get(b"M4AG"),
                b"m4againrs version=1 gain_steps=2 gain_step_db=1.5",
            )

    def test_file_api_rewrites_chunk_offsets_when_moov_growth_moves_media(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "faststart.m4a"
            dst = Path(tmpdir) / "faststart_out.m4a"
            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-i",
                    str(TEST_M4A),
                    "-c",
                    "copy",
                    "-movflags",
                    "faststart",
                    str(src),
                ],
                check=True,
            )

            src_bytes = src.read_bytes()
            src_moov = _find_box(src_bytes, b"moov")
            src_mdat = _find_box(src_bytes, b"mdat")
            self.assertIsNotNone(src_moov)
            self.assertIsNotNone(src_mdat)
            self.assertLess(src_moov[0], src_mdat[0])
            original_ranges = _sample_byte_ranges(src_bytes)

            modified = m4againrs.aac_apply_gain_file(str(src), str(dst), 2)
            self.assertGreater(modified, 0)

            dst_bytes = dst.read_bytes()
            dst_moov = _find_box(dst_bytes, b"moov")
            dst_mdat = _find_box(dst_bytes, b"mdat")
            self.assertIsNotNone(dst_moov)
            self.assertIsNotNone(dst_mdat)

            moov_growth = dst_moov[1] - src_moov[1]
            self.assertGreater(moov_growth, 0)
            self.assertEqual(dst_mdat[0], src_mdat[0] + moov_growth)

            rewritten_ranges = _sample_byte_ranges(dst_bytes)
            self.assertEqual(len(rewritten_ranges), len(original_ranges))
            for (before_off, before_size), (after_off, after_size) in zip(
                original_ranges, rewritten_ranges
            ):
                self.assertEqual(after_size, before_size)
                self.assertEqual(after_off, before_off + moov_growth)


class ShortWindowAacTest(unittest.TestCase):
    def test_file_api_patches_short_window_stereo_frames_and_ffmpeg_decodes(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "short_window.m4a"
            dst = Path(tmpdir) / "short_window_gain.m4a"

            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-f",
                    "lavfi",
                    "-i",
                    (
                        "aevalsrc="
                        "'if(lt(mod(t,0.25),0.018),0.95*sin(2*PI*2800*t),0.04*sin(2*PI*440*t))|"
                        "if(lt(mod(t,0.25),0.018),0.95*sin(2*PI*3600*t),0.04*sin(2*PI*660*t))'"
                        ":s=32000:d=3"
                    ),
                    "-c:a",
                    "aac",
                    "-b:a",
                    "96k",
                    str(src),
                ],
                check=True,
            )

            sample_count = len(_sample_byte_ranges(src.read_bytes()))
            modified = m4againrs.aac_apply_gain_file(str(src), str(dst), 5)
            self.assertEqual(modified, sample_count * 2)

            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-i",
                    str(dst),
                    "-f",
                    "null",
                    "-",
                ],
                check=True,
            )


class TaggedFixtureTest(unittest.TestCase):
    """Same guarantees as MetadataPreservationTest, but exercised against an
    ffmpeg-generated fixture with 8 iTunes tags (title, artist, album, date,
    encoder, comment, genre, track) — richer than the bundled test.m4a.

    The fixture is committed under testdata/; if it's missing, tests fail
    loudly rather than skipping. Regenerate with testdata/regenerate.sh."""

    EXPECTED_TAGS = {
        b"\xa9nam": b"Gain Test Tone",
        b"\xa9ART": b"m4againrs",
        b"\xa9alb": b"Fixtures",
        b"\xa9day": b"2026",
        b"\xa9gen": b"Electronic",
        b"\xa9cmt": b"Used to verify metadata survives gain adjustment.",
        # ©too (encoder) is set by ffmpeg and version-dependent (e.g.
        # "Lavf61.7.100"); we only assert it's present and round-trips.
        # trkn has binary packed bytes; likewise — checked via round-trip.
    }

    def test_fixture_has_expected_tags(self):
        tags = _parse_itunes_tags(TAGGED_M4A.read_bytes())
        for name, value in self.EXPECTED_TAGS.items():
            self.assertEqual(tags.get(name), value, f"{name!r} missing or wrong")
        self.assertIn(b"\xa9too", tags)
        self.assertIn(b"trkn", tags)

    def test_file_api_preserves_tags_and_adds_custom_gain_tag(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "tagged.m4a"
            dst = Path(tmpdir) / "tagged_out.m4a"
            shutil.copy2(TAGGED_M4A, src)
            src_original = src.read_bytes()
            before = _parse_itunes_tags(src_original)

            modified = m4againrs.aac_apply_gain_file(str(src), str(dst), 4)
            self.assertGreater(modified, 0)

            # src untouched
            self.assertEqual(src.read_bytes(), src_original)
            # dst preserves existing tags and adds ffprobe-visible gain metadata
            after = _parse_itunes_tags(dst.read_bytes())
            expected = dict(before)
            expected[b"M4AG"] = b"m4againrs version=1 gain_steps=4 gain_step_db=1.5"
            self.assertEqual(expected, after)


if __name__ == "__main__":
    unittest.main()
